#spring:
#  security:
#    user:
#      email: admin@admin.com
#      password: adminpassword
#      role: ADMIN
#  application:
#    name: security
#  datasource:
#    initialization-mode: always
#    username: admin
#    password: admin1234
#    url: jdbc:mysql://database-1.coz3uh2yaw2j.us-east-2.rds.amazonaws.com/appointmentsdb
#  jpa:
#    properties:
#      javax.persistence.schema-generation.database.action: update
#  cloud:
#    gateway:
#      routes:
#        - id: client
#          uri: lb://client
#          predicates:
#            - Path=/client/**
#          filters:
#            - StripPrefix=1
#        - id: staff
#          uri: lb://staff
#          predicates:
#            - Path=/staff/**
#          filters:
#            - StripPrefix=1
#        - id: appointment
#          uri: lb://appointment
#          predicates:
#            - Path=/appointment/**
#          filters:
#            - StripPrefix=1
#        - id: security
#          uri: lb://security
#          predicates:
#            - Path=/security/**
#          filters:
#            - StripPrefix=1
#server:
#  port: 8090
#eureka:
#  client:
#    serviceUrl:
##      defaultZone: 'http://localhost:8761/eureka/'
#      defaultZone: 'https://eureka-server-ms-113f8fccf842.herokuapp.com/eureka/'
#    fetch-registry: true
#    register-with-eureka: true
#  instance:
#    hostname: localhost
#    preferIpAddress: true
#    appname: security
#


spring:
  security:
    user:
      email: admin@admin.com
      password: adminpassword
      role: ADMIN
  application:
    name: security
  datasource:
    initialization-mode: always
    username: admin
    password: admin1234
    url: jdbc:mysql://database-1.coz3uh2yaw2j.us-east-2.rds.amazonaws.com/appointmentsdb
  jpa:
    properties:
      javax.persistence.schema-generation.database.action: update
  cloud:
    gateway:
      routes:
        - id: client
          uri: lb://client
          predicates:
            - Path=/client/**
          filters:
            - StripPrefix=1
        - id: staff
          uri: lb://staff
          predicates:
            - Path=/staff/**
          filters:
            - StripPrefix=1
        - id: appointment
          uri: lb://appointment
          predicates:
            - Path=/appointment/**
          filters:
            - StripPrefix=1
        - id: security
          uri: lb://security
          predicates:
            - Path=/security/**
          filters:
            - StripPrefix=1

server:
  port: ${PORT:8090}

eureka:
  client:
    serviceUrl:
      defaultZone: 'https://eureka-server-ms-113f8fccf842.herokuapp.com/eureka/'
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
    appname: security
    hostname: ${DYNO}
    nonSecurePortEnabled: true
    nonSecurePort: ${PORT}
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
